import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs"
import { dirname, join, relative, resolve } from "node:path"

export interface VaultData {
  mdFiles: Array<readonly [string, string]>
  assetFiles: Array<readonly [string, string]>
  cssBundle: string
  appearanceOrder: string[]
}

function orderCssFiles(files: string[], ordered: string[] | null): string[] {
  if (!ordered || ordered.length === 0) {
    return files
  }
  const set = new Set(files)
  const normalized = ordered.map((f) => (f.endsWith(".css") ? f : `${f}.css`)).filter((f) => set.has(f))
  const remaining = files.filter((f) => !normalized.includes(f))
  return [...normalized, ...remaining]
}

function cleanCss(css: string): string {
  return css
    .split("\n")
    .filter((line) => line.trim() !== "")
    .join("\n")
}

function collect(dir: string, base: string, out: string[], pick: (name: string) => boolean): void {
  if (!existsSync(dir)) {
    return
  }
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, e.name)
    if (e.isDirectory()) {
      if (e.name.startsWith(".") || e.name === "node_modules") {
        continue
      }
      collect(full, base, out, pick)
    } else if (e.isFile() && pick(e.name)) {
      out.push(relative(base, full))
    }
  }
}

const ASSET_EXTS = new Set([".png", ".jpg", ".jpeg", ".gif", ".webp", ".svg", ".ico", ".avif"])

export function parseArgs(defaultVaultRoot: string, defaultOutFile: string): { vaultRoot: string; outFile: string } {
  const args = process.argv.slice(2)
  let vaultRoot = defaultVaultRoot
  let outFile = defaultOutFile
  for (let i = 0; i < args.length; i++) {
    if (args[i] === "--vault" && args[i + 1]) {
      vaultRoot = resolve(process.cwd(), args[i + 1] as string)
      i++
    } else if (args[i] === "--out" && args[i + 1]) {
      outFile = resolve(process.cwd(), args[i + 1] as string)
      i++
    } else if (!args[i]!.startsWith("-") && i === 0) {
      vaultRoot = resolve(process.cwd(), args[i] as string)
    }
  }
  return { vaultRoot, outFile }
}

export function collectVault(vaultRoot: string, includeAssets: boolean): VaultData {
  const mdFiles: string[] = []
  collect(vaultRoot, vaultRoot, mdFiles, (name) => name.endsWith(".md"))
  mdFiles.sort()

  const cssDir = join(vaultRoot, ".obsidian/snippets")
  let cssFiles: string[] = []
  try {
    cssFiles = readdirSync(cssDir)
      .filter((f) => f.endsWith(".css"))
      .sort()
  } catch {
    // No snippets directory: bundle without CSS.
  }

  let ordered: string[] | null = null
  const appearancePath = join(vaultRoot, ".obsidian/appearance.json")
  try {
    if (existsSync(appearancePath)) {
      const raw = readFileSync(appearancePath, "utf-8")
      const data = JSON.parse(raw)
      if (Array.isArray(data.enabledCssSnippets)) {
        ordered = data.enabledCssSnippets as string[]
      }
    }
  } catch {
    // Unreadable appearance.json: fall back to alphabetical CSS order.
  }

  cssFiles = orderCssFiles(cssFiles, ordered)

  const cssBundle = cleanCss(
    cssFiles
      .map((f) => {
        try {
          return readFileSync(join(cssDir, f), "utf-8")
        } catch {
          return ""
        }
      })
      .join("\n"),
  )

  const mdEntries = mdFiles.map((rel) => [rel, readFileSync(join(vaultRoot, rel), "utf-8")] as const)

  let assetEntries: Array<readonly [string, string]> = []
  if (includeAssets) {
    const assetFiles: string[] = []
    collect(vaultRoot, vaultRoot, assetFiles, (name) => {
      const ext = `.${name.split(".").pop()!.toLowerCase()}`
      return ASSET_EXTS.has(ext)
    })
    assetFiles.sort()
    assetEntries = assetFiles.map((rel) => [rel, readFileSync(join(vaultRoot, rel)).toString("base64")] as const)
  }

  return { mdFiles: mdEntries, assetFiles: assetEntries, cssBundle, appearanceOrder: ordered ?? [] }
}

export function writeBundle(outFile: string, data: VaultData, includeAssets: boolean): void {
  mkdirSync(dirname(outFile), { recursive: true })
  const assetsLine = includeAssets
    ? `\nexport const assetFiles: Record<string, string> = ${JSON.stringify(Object.fromEntries(data.assetFiles), null, 2)}`
    : ""
  const out = `// AUTO-GENERATED by collect-vault — do not edit
export const cssBundle = ${JSON.stringify(data.cssBundle)}
export const vaultFiles: Record<string, string> = ${JSON.stringify(Object.fromEntries(data.mdFiles), null, 2)}${assetsLine}
export const appearanceOrder = ${JSON.stringify(data.appearanceOrder, null, 2)}
`
  writeFileSync(outFile, out)
  console.log(`generated ${data.mdFiles.length} md files, ${data.assetFiles.length} assets -> ${outFile}`)
}
