import { readFileSync, readdirSync, existsSync, writeFileSync, mkdirSync } from "node:fs"
import { join, relative, dirname, resolve } from "node:path"
import { fileURLToPath } from "node:url"
import { orderCssFiles, cleanCss } from "@gyorgygutai/processor"

const __dirname = dirname(fileURLToPath(import.meta.url))
const defaultVaultRoot = join(__dirname, "../../../vault")
const defaultOutFile = join(__dirname, "./generated/bundle.ts")

function collectMd(dir: string, base: string, out: string[]) {
  if (!existsSync(dir)) {
    return
  }
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, e.name)
    if (e.isDirectory()) {
      if (e.name.startsWith(".") || e.name === "node_modules") {
        continue
      }
      collectMd(full, base, out)
    } else if (e.isFile() && e.name.endsWith(".md")) {
      out.push(relative(base, full))
    }
  }
}

const ASSET_EXTS = new Set([".png", ".jpg", ".jpeg", ".gif", ".webp", ".svg", ".ico", ".avif"])

function collectAssets(dir: string, base: string, out: string[]) {
  if (!existsSync(dir))
    return
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, e.name)
    if (e.isDirectory()) {
      if (e.name.startsWith(".") || e.name === "node_modules")
        continue
      collectAssets(full, base, out)
    } else if (e.isFile()) {
      const ext = "." + e.name.split(".").pop()!.toLowerCase()
      if (ASSET_EXTS.has(ext))
        out.push(relative(base, full))
    }
  }
}

function parseArgs(): { vaultRoot: string; outFile: string } {
  const args = process.argv.slice(2)
  let vaultRoot = defaultVaultRoot
  let outFile = defaultOutFile
  for (let i = 0; i < args.length; i++) {
    if (args[i] === "--vault" && args[i + 1]) {
      vaultRoot = resolve(process.cwd(), args[i + 1] as string)
      i++
    } else if (args[i] === "--out" && args[i + 1]) {
      outFile = resolve(process.cwd(), args[i + 1] as string)
      i++
    } else if (!args[i]!.startsWith("-") && i === 0) {
      vaultRoot = resolve(process.cwd(), args[i] as string)
    }
  }
  return { vaultRoot, outFile }
}

const { vaultRoot, outFile } = parseArgs()

const mdFiles: string[] = []
collectMd(vaultRoot, vaultRoot, mdFiles)
mdFiles.sort()

const cssDir = join(vaultRoot, ".obsidian/snippets")
let cssFiles: string[] = []
try {
  cssFiles = readdirSync(cssDir)
    .filter((f) => f.endsWith(".css"))
    .sort()
} catch {}

let ordered: string[] | null = null
const appearancePath = join(vaultRoot, ".obsidian/appearance.json")
try {
  if (existsSync(appearancePath)) {
    const raw = readFileSync(appearancePath, "utf-8")
    const data = JSON.parse(raw)
    if (Array.isArray(data.enabledCssSnippets)) {
      ordered = data.enabledCssSnippets as string[]
    }
  }
} catch {}

cssFiles = orderCssFiles(cssFiles, ordered)

const cssBundle = cleanCss(
  cssFiles
    .map((f) => {
      try {
        return readFileSync(join(cssDir, f), "utf-8")
      } catch {
        return ""
      }
    })
    .join("\n"),
)

const vaultEntries = mdFiles.map((rel) => {
  const content = readFileSync(join(vaultRoot, rel), "utf-8")
  return [rel, content] as const
})

const assetFilesList: string[] = []
collectAssets(vaultRoot, vaultRoot, assetFilesList)
assetFilesList.sort()
const assetEntries = assetFilesList.map((rel) => {
  const buf = readFileSync(join(vaultRoot, rel))
  return [rel, buf.toString("base64")] as const
})

mkdirSync(dirname(outFile), { recursive: true })

const out = `// AUTO-GENERATED by worker/bundleVaultIntoWorker.ts — do not edit
export const cssBundle = ${JSON.stringify(cssBundle)}
export const vaultFiles: Record<string, string> = ${JSON.stringify(Object.fromEntries(vaultEntries), null, 2)}
export const assetFiles: Record<string, string> = ${JSON.stringify(Object.fromEntries(assetEntries), null, 2)}
export const appearanceOrder = ${JSON.stringify(ordered ?? [], null, 2)}
`

writeFileSync(outFile, out)
console.log(`generated ${mdFiles.length} md files, ${assetFilesList.length} assets, ${cssFiles.length} css files -> ${outFile}`)