import { readFileSync, readdirSync, existsSync, writeFileSync, mkdirSync } from "node:fs"
import { join, relative, dirname } from "node:path"
import { fileURLToPath } from "node:url"

const __dirname = dirname(fileURLToPath(import.meta.url))
const defaultVaultRoot = join(__dirname, "../..")
const defaultOutFile = join(__dirname, "./generated/bundle.ts")

function collectMd(dir: string, base: string, out: string[]) {
  if (!existsSync(dir)) {
    return
  }
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, e.name)
    if (e.isDirectory()) {
      if (e.name.startsWith(".") || e.name === "node_modules" || e.name === ".website") {
        continue
      }
      collectMd(full, base, out)
    } else if (e.isFile() && e.name.endsWith(".md")) {
      out.push(relative(base, full))
    }
  }
}

function parseArgs(): { vaultRoot: string; outFile: string } {
  const args = process.argv.slice(2)
  let vaultRoot = defaultVaultRoot
  let outFile = defaultOutFile
  for (let i = 0; i < args.length; i++) {
    if (args[i] === "--vault" && args[i + 1]) {
      vaultRoot = join(process.cwd(), args[i + 1] as string).includes(":") ? (args[i + 1] as string) : join(process.cwd(), args[i + 1] as string)
      if ((args[i + 1] as string).startsWith("/")) {
        vaultRoot = args[i + 1] as string
      }
      i++
    } else if (args[i] === "--out" && args[i + 1]) {
      outFile = args[i + 1] as string
      i++
    } else if (!args[i]!.startsWith("-") && i === 0) {
      vaultRoot = args[i] as string
    }
  }
  if (vaultRoot.startsWith("./") || vaultRoot.startsWith("../")) {
    vaultRoot = join(process.cwd(), vaultRoot)
  }
  return { vaultRoot, outFile }
}

const { vaultRoot, outFile } = parseArgs()

const mdFiles: string[] = []
collectMd(vaultRoot, vaultRoot, mdFiles)
mdFiles.sort()

const cssDir = join(vaultRoot, ".obsidian/snippets")
let cssFiles: string[] = []
try {
  cssFiles = readdirSync(cssDir)
    .filter((f) => f.endsWith(".css"))
    .sort()
} catch {}

let ordered: string[] | null = null
const appearancePath = join(vaultRoot, ".obsidian/appearance.json")
try {
  if (existsSync(appearancePath)) {
    const raw = readFileSync(appearancePath, "utf-8")
    const data = JSON.parse(raw)
    if (Array.isArray(data.enabledCssSnippets)) {
      ordered = data.enabledCssSnippets as string[]
    }
  }
} catch {}

if (ordered && ordered.length > 0) {
  const set = new Set(cssFiles)
  const orderedFiles = ordered.filter((f) => set.has(f) || set.has(f + ".css") || set.has(f.replace(/\.css$/, "")))
  const normalizedOrdered = orderedFiles.map((f) => (f.endsWith(".css") ? f : f + ".css")).filter((f) => set.has(f))
  const remaining = cssFiles.filter((f) => !normalizedOrdered.includes(f))
  cssFiles = [...normalizedOrdered, ...remaining]
}

const cssBundle = cssFiles
  .map((f) => {
    try {
      return readFileSync(join(cssDir, f), "utf-8")
    } catch {
      return ""
    }
  })
  .join("\n")

const vaultEntries = mdFiles.map((rel) => {
  const content = readFileSync(join(vaultRoot, rel), "utf-8")
  return [rel, content] as const
})

mkdirSync(dirname(outFile), { recursive: true })

const out = `// AUTO-GENERATED by worker/bundleVaultIntoWorker.ts — do not edit
export const cssBundle = ${JSON.stringify(cssBundle)}
export const vaultFiles: Record<string, string> = ${JSON.stringify(Object.fromEntries(vaultEntries), null, 2)}
export const appearanceOrder = ${JSON.stringify(ordered ?? [], null, 2)}
`

writeFileSync(outFile, out)
const legacyOut = join(dirname(outFile), "vault.ts")
writeFileSync(legacyOut, out.replace("bundleVaultIntoWorker.ts", "bundleVaultIntoWorker.ts"))
console.log(`generated ${mdFiles.length} md files, ${cssFiles.length} css files -> ${outFile}`)
