import { readFileSync, readdirSync, existsSync, writeFileSync, mkdirSync } from "node:fs"
import { join, relative } from "node:path"
import { fileURLToPath } from "node:url"
import { dirname } from "node:path"

const __dirname = dirname(fileURLToPath(import.meta.url))
const vaultRoot = join(__dirname, "../..")
const outFile = join(__dirname, "./generated/vault.ts")

function collectMd(dir: string, base: string, out: string[]) {
  if (!existsSync(dir)) {
    return
  }
  const entries = readdirSync(dir, { withFileTypes: true })
  for (const e of entries) {
    const full = join(dir, e.name)
    if (e.isDirectory()) {
      if (e.name.startsWith(".") || e.name === "node_modules" || e.name === ".website") {
        continue
      }
      if (e.name === "peach" || e.name === "research" || e.name === "img") {
        continue
      }
      collectMd(full, base, out)
    } else if (e.isFile() && e.name.endsWith(".md")) {
      out.push(relative(base, full))
    }
  }
}

const mdFiles: string[] = []
for (const p of ["index.md", "links.md"]) {
  const full = join(vaultRoot, p)
  if (existsSync(full)) {
    mdFiles.push(p)
  }
}
collectMd(join(vaultRoot, "content"), vaultRoot, mdFiles)
collectMd(join(vaultRoot, "pdf"), vaultRoot, mdFiles)

mdFiles.sort()

const cssDir = join(vaultRoot, ".obsidian/snippets")
let cssFiles: string[] = []
try {
  cssFiles = readdirSync(cssDir)
    .filter((f) => f.endsWith(".css"))
    .sort()
} catch {}

let ordered: string[] | null = null
const appearancePath = join(vaultRoot, ".obsidian/appearance.json")
try {
  if (existsSync(appearancePath)) {
    const raw = readFileSync(appearancePath, "utf-8")
    const data = JSON.parse(raw)
    if (Array.isArray(data.enabledCssSnippets)) {
      ordered = data.enabledCssSnippets as string[]
    }
  }
} catch {}

if (ordered && ordered.length > 0) {
  const set = new Set(cssFiles)
  const orderedFiles = ordered
    .filter((f) => set.has(f) || set.has(f + ".css") || set.has(f.replace(/\.css$/, "")))
  const normalizedOrdered = orderedFiles.map((f) => (f.endsWith(".css") ? f : f + ".css")).filter((f) => set.has(f))
  const remaining = cssFiles.filter((f) => !normalizedOrdered.includes(f))
  cssFiles = [...normalizedOrdered, ...remaining]
}

const cssBundle = cssFiles
  .map((f) => {
    try {
      return readFileSync(join(cssDir, f), "utf-8")
    } catch {
      return ""
    }
  })
  .join("\n")

const vaultEntries = mdFiles.map((rel) => {
  const content = readFileSync(join(vaultRoot, rel), "utf-8")
  return [rel, content] as const
})

mkdirSync(dirname(outFile), { recursive: true })

const out = `// AUTO-GENERATED by worker/generateVault.ts — do not edit
export const cssBundle = ${JSON.stringify(cssBundle)}
export const vaultFiles: Record<string, string> = ${JSON.stringify(Object.fromEntries(vaultEntries), null, 2)}
export const appearanceOrder = ${JSON.stringify(ordered ?? [], null, 2)}
`

writeFileSync(outFile, out)
console.log(`generated ${mdFiles.length} md files, ${cssFiles.length} css files -> ${outFile}`)
